ESTA ES UNA API MUY RUDIMENTARIA. 

Carece de entorno grÃ¡fico o de todas esas cosas bonitas que atraen presupuesto. 

No funciona con botones sino con dolor. 

Sin embargo, es el punto de partida.

In [2]:
!pip install pandas

Collecting pandas
  Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\avril\octavo_semestre\repositorio_actividades_bloque_final\actividades_cc\act_semana_2\.venv\lib\site-packages (from pandas) (1.23.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\avril\octavo_semestre\repositorio_actividades_bloque_final\actividades_cc\act_semana_2\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\avril\octavo_semestre\repositorio_actividades_bloque_final\actividades_cc\act_semana_2\.venv\lib\site-packages (from pandas) (2025.2)
Collecting tzdata>=2022.7 (from pandas)
  Using cached tzdata-2025.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\avril\octavo_semestre\repositorio_actividades_bloque_final\actividades_cc\act_semana_2\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Installing collected packages: tzdata, pandas
Successfully installed pandas-2.2.3 tzdata-2025.2

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd

#input_data = input("Introduce path for data")
data = pd.read_csv("../prueba.csv").drop(["Unnamed: 0", "Bankrupt?"], axis=1)
data_dict = data.to_dict(orient='list')

data

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,339932.913561,...,-20803.840865,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260
1,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,339868.922278,...,-20816.707256,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588
2,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,340061.212601,...,-20231.915888,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872
3,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,339795.500035,...,-21387.657854,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429
4,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,339927.723368,...,-20465.789236,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504
5,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,339858.162122,...,-20915.443338,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732
6,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,339880.188795,...,-20859.146789,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195
7,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,339766.067843,...,-21519.365535,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833
8,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,339967.599241,...,-20298.628357,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626
9,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,340042.477270,...,-20934.411461,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140

In [4]:
import json

#Formateado para la API:
data_json = json.dumps({"data": [data_dict]})

suri = open("uri.json", "r")
scoring_uri = json.load(suri)["URI"][0]
suri.close()

In [5]:
## La API per-sÃ©:

headers = {"Content-Type": "application/json"}
import requests
response = requests.post(scoring_uri, data=data_json, headers=headers)

if response.status_code == 200:
  result = json.loads(response.json())
  print(result)
  data["Exited"] = result
  display(data)
else:
  print(f"Error: {response.text}")

{'error': "[ERROR] Expected 'data' to be a list of feature dictionaries."}

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability,Exited
0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,339932.913561,...,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260,NaN
1,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,339868.922278,...,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588,NaN
2,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,340061.212601,...,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872,NaN
3,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,339795.500035,...,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429,NaN
4,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,339927.723368,...,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504,NaN
5,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,339858.162122,...,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732,NaN
6,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,339880.188795,...,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195,NaN
7,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,339766.067843,...,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833,NaN
8,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,339967.599241,...,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626,NaN
9,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,340042.477270,...,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140,NaN