In [1]:
import pandas as pd

#input_data = input("Introduce path for data")
data = pd.read_csv("../model/SalesLT.csv").drop(["Unnamed: 0"], axis=1)
data.head()

,CustomerID,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,ModifiedDate
0,1,False,Mr.,Orlando,N.,Gee,NaN,A Bike Store,adventure-works\pamela0,orlando0@adventure-works.com,245-555-0173,L/Rlwxzp4w7RWmEgXX+/A7cXaePEPcp+KwQhl2fJL7w=,1KjXYs4=,3F5AE95E-B87D-4AED-95B4-C3797AFCB74F,2005-08-01 00:00:00.000
1,2,False,Mr.,Keith,NaN,Harris,NaN,Progressive Sports,adventure-works\david8,keith0@adventure-works.com,170-555-0127,YPdtRdvqeAhj6wyxEsFdshBDNXxkCXn+CRgbvJItknw=,fs1ZGhY=,E552F657-A9AF-4A7D-A645-C429D6E02491,2006-08-01 00:00:00.000
2,3,False,Ms.,Donna,F.,Carreras,NaN,Advanced Bike Components,adventure-works\jillian0,donna0@adventure-works.com,279-555-0130,LNoK27abGQo48gGue3EBV/UrlYSToV0/s87dCRV7uJk=,YTNH5Rw=,130774B1-DB21-4EF3-98C8-C104BCD6ED6D,2005-09-01 00:00:00.000
3,4,False,Ms.,Janet,M.,Gates,NaN,Modular Cycle Systems,adventure-works\jillian0,janet1@adventure-works.com,710-555-0173,ElzTpSNbUW1Ut+L5cWlfR7MF6nBZia8WpmGaQPjLOJA=,nm7D5e4=,FF862851-1DAA-4044-BE7C-3E85583C054D,2006-07-01 00:00:00.000
4,5,False,Mr.,Lucy,NaN,Harrington,NaN,Metropolitan Sports Supply,adventure-works\shu0,lucy0@adventure-works.com,828-555-0186,KJqV15wsX3PG8TS5GSddp6LFFVdd3CoRftZM/tP0+R4=,cNFKU4w=,83905BDC-6F5E-4F71-B162-C98DA069F38A,2006-09-01 00:00:00.000

In [3]:
import pandas as pd
import json

data_dict = data.to_dict(orient='list')

#Formateado para la API:
data_json = json.dumps({"data": [data_dict]})

suri = open("uri.json", "r")
scoring_uri = json.load(suri)["URI"][0]
suri.close()

In [4]:
import pandas as pd
import json
import requests
data = pd.read_csv("../model/SalesLT.csv").drop(["Unnamed: 0"], axis=1)
data.dropna(inplace=True)
data = data.head()
data_dict = data.to_dict(orient='records') 
data_json = json.dumps({"data": data_dict})  

headers = {"Content-Type": "application/json"}
response = requests.post(scoring_uri, data=data_json, headers=headers)

# Manejar la respuesta
if response.status_code == 200:
    result = json.loads(response.json())  
    print(result)
    data["Predictions"] = result["predictions"] 
    display(data)
else:
    print(f"Error: {response.text}")

{'predictions': [1155381408.0, 1157142240.0, 1155645792.0, 1135804896.0, 1140689952.0]}

,CustomerID,NameStyle,Title,FirstName,MiddleName,LastName,Suffix,CompanyName,SalesPerson,EmailAddress,Phone,PasswordHash,PasswordSalt,rowguid,ModifiedDate,Predictions
9,12,False,Mr.,Johnny,A.,Caprio,Jr.,Bikes and Motorbikes,adventure-works\garrett1,johnny0@adventure-works.com,112-555-0191,jtF9jBoFYeJTaET7x+eJDkd7BzMz15Wo9odbGPBaIak=,wVLnvHo=,947BCAF1-1F32-44F3-B9C3-0011F95FBE54,2006-08-01 00:00:00.000,1.155381e+09
10,16,False,Mr.,Christopher,R.,Beck,Jr.,Bulk Discount Store,adventure-works\jae0,christopher1@adventure-works.com,1 (11) 500 555-0132,sKt9daCzEEKWAzivEGPOp8tmaM1R3I+aJfcBjzJRFLo=,8KfYx/4=,C9381589-D31C-4EFE-8978-8D3449EB1F0F,2006-09-01 00:00:00.000,1.157142e+09
95,151,False,Mr.,Walter,J.,Brian,IV,Futuristic Bikes,adventure-works\shu0,walter0@adventure-works.com,163-555-0155,NN11OHHxrOm6r8lPyhXuBk13QMD+8tph5PIdJ4t0JmY=,PiILPfc=,7F2891F7-DD88-470B-95AE-CC9A7D732B1F,2006-09-01 00:00:00.000,1.155646e+09
98,156,False,Mr.,Lester,J.,Bowman,Sr.,Metal Processing Company,adventure-works\garrett1,lester0@adventure-works.com,844-555-0112,+CFHIbYlE+nsmSbCpJOTLZXChbtYA9JzdSnd1Qejk5g=,w7ec7iI=,CFFFAAFB-98DC-4392-84F9-FB3229F35265,2005-09-01 00:00:00.000,1.135805e+09
108,173,False,Mr.,Rudolph,J.,Dillon,Sr.,Sundry Sporting Goods,adventure-works\josé1,rudolph0@adventure-works.com,722-555-0169,hynkaEM/LxC86JGG4q4AGgiar6iWoIu5bLVB3gFq2RM=,DUDd/5g=,FDC12E98-898B-4C22-972F-F0EBFBFCB7B0,2005-09-01 00:00:00.000,1.140690e+09